name: Python Unit Tests & Coverage

on: [pull_request]

jobs:
  test:
    name: Python Unit Tests & Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python Environemnt
        uses: actions/setup-python@v1
        with:
          python-version: 3.12

      - name: Install Requirements
        run: |
          make install_requirements

      - name: Run Tests
        run: |
          make test-coverage
